version: "3"

services:
  djan:
    build: ./dj
    env_file:
      - ./env/dc.env
      - ./env/django/dj.env
    volumes:
      - static_files:${DJANGO_STATIC_FOLDER}
      - media_files:${DJANGO_MEDIA_FOLDER}

  ng:
    build: ./ngi
    env_file:
      - ./env/dc.env
    volumes:
      - static_files:${NGINX_STATIC_FOLDER}
      - media_files:${NGINX_MEDIA_FOLDER}
    ports:
      - "${OUTER_PORT}:${NGINX_LISTEN_PORT}"


volumes:
  static_files:
  media_files: