version: "3"

services:
  djan:
    build: ./dj
    env_file:
      - ./env/dc.env
      - ./env/django/dj.env
    volumes:
      - static_files:${DJANGO_STATIC_FOLDER}
      - media_files:${DJANGO_MEDIA_FOLDER}

  nginx:
    build: ./nginx
    env_file:
      - ./env/dc.env
    volumes:
      - static_files:${NGINX_STATIC_FOLDER}
      - media_files:${NGINX_MEDIA_FOLDER}
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email redmaxx4@gmail.com -d redslow-services.ru --agree-tos
    depends_on:
      - nginx
volumes:
  static_files:
  media_files: